/*
 * DialogConfiguration.java
 *
 * Created on 31 décembre 2008, 23:29
 */

package musicwriter;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author  proprietaire
 */
public class DialogConfiguration extends javax.swing.JDialog {

    /** Creates new form DialogConfiguration */
    public DialogConfiguration(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        remplirListeEntreeMIDI();
        remplirListeSortieMIDI();
        
    }

    int machineSortieMIDINumeroGet() {
        return listeSortieMIDI.getSelectedIndex();
    }
    
    
    private void remplirListeEntreeMIDI()
    {
        ArrayList<String> noms = InterfaceMIDI.getMachinesEntreesMIDIDisponiblesNomsListe();     
        DefaultListModel model = new DefaultListModel();    
        for(String s : noms)   {  model.addElement(s); }
        listeEntreeMIDI.setModel(model);
        listeEntreeMIDI.setSelectedIndex(0);
    }
    
    
    private void remplirListeSortieMIDI()
    {
        ArrayList<String> noms = InterfaceMIDI.getMachinesSortiesMIDIDisponiblesNomsListe();     
        DefaultListModel model = new DefaultListModel();    
        for(String s : noms)   {  model.addElement(s); }
        listeSortieMIDI.setModel(model);
        listeSortieMIDI.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listeSortieMIDI = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeEntreeMIDI = new javax.swing.JList();
        boutonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(DialogConfiguration.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listeSortieMIDI.setName("listeSortieMIDI"); // NOI18N
        jScrollPane1.setViewportView(listeSortieMIDI);

        getContentPane().add(jScrollPane1);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        listeEntreeMIDI.setName("listeEntreeMIDI"); // NOI18N
        jScrollPane2.setViewportView(listeEntreeMIDI);

        getContentPane().add(jScrollPane2);

        boutonOK.setText(resourceMap.getString("boutonOK.text")); // NOI18N
        boutonOK.setName("boutonOK"); // NOI18N
        boutonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonOKActionPerformed(evt);
            }
        });
        getContentPane().add(boutonOK);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void boutonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonOKActionPerformed
    setVisible(false);
}//GEN-LAST:event_boutonOKActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogConfiguration dialog = new DialogConfiguration(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listeEntreeMIDI;
    private javax.swing.JList listeSortieMIDI;
    // End of variables declaration//GEN-END:variables

}
