/*
 * HelpPanel.java
 *
 * Created on 27 août 2008, 12:24
 */

package musicwriter;

import java.io.IOException;

/**
 *
 * @author  proprietaire
 */
public class HelpPanel extends javax.swing.JPanel {
    /** Creates new form HelpPanel */
    public HelpPanel() {
        initComponents();
    }
    
    
    
    void page_show(java.net.URL helpURL)
    {
         if (helpURL != null) {
            try {
                jEditorPane.setPage(helpURL);
            } catch (IOException e) {
                System.err.println("Attempted to read a bad URL: " + helpURL);
            }
        } else {
            System.err.println("Couldn't find file: " + helpURL.getFile());
        } 
    }
    
    
    
    void page_show(String name)
    {
        java.net.URL helpURL = getClass().getResource("resources/help/" + 
                                name);
        
        page_show(helpURL);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane = new javax.swing.JEditorPane();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jEditorPane.setEditable(false);
        jEditorPane.setName("jEditorPane"); // NOI18N
        jEditorPane.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                jEditorPaneHyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jEditorPane);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jEditorPaneHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_jEditorPaneHyperlinkUpdate
// TODO add your handling code here:
         page_show(evt.getURL());
}//GEN-LAST:event_jEditorPaneHyperlinkUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
