/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TempoDialog.java
 *
 * Created on 12 févr. 2010, 10:50:20
 */

package musicwriter.dialogs;

import musicwriter.ElementMusicalTempo;
import musicwriter.Moment;
import musicwriter.Rational;
import org.jdesktop.application.Action;

/**
 *
 * @author Ancmin
 */
public class TempoDialog extends javax.swing.JDialog {

    static private  Moment moment = new Moment(new Rational(0, 1));
    private ElementMusicalTempo tempo = null;

    public ElementMusicalTempo getTempo() {
        return tempo;
    }

    /** Creates new form TempoDialog */
    public TempoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getResourceMap(TempoDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jButton1.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicwriter/dialogs/resources/escarguepard0.png"))); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(musicwriter.MusicwriterApp.class).getContext().getActionMap(TempoDialog.class, this);
        jButton2.setAction(actionMap.get("adagio")); // NOI18N
        jButton2.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicwriter/dialogs/resources/escarguepard2.png"))); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jButton3.setAction(actionMap.get("andante")); // NOI18N
        jButton3.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicwriter/dialogs/resources/escarguepard3.png"))); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        jButton4.setAction(actionMap.get("andantino")); // NOI18N
        jButton4.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicwriter/dialogs/resources/escarguepard4.png"))); // NOI18N
        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N

        jButton5.setAction(actionMap.get("allegretto")); // NOI18N
        jButton5.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicwriter/dialogs/resources/escarguepard5.png"))); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N

        jButton6.setAction(actionMap.get("allegro")); // NOI18N
        jButton6.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicwriter/dialogs/resources/escarguepard6.png"))); // NOI18N
        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N

        jButton7.setAction(actionMap.get("presto")); // NOI18N
        jButton7.setFont(resourceMap.getFont("jButton4.font")); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicwriter/dialogs/resources/guepard.png"))); // NOI18N
        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tempo = new ElementMusicalTempo(moment, 30, "Lento");
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TempoDialog dialog = new TempoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void adagio() {
        tempo = new ElementMusicalTempo(moment, 40, "Adagio");
        setVisible(false);
    }

    @Action
    public void andante() {
        tempo = new ElementMusicalTempo(moment, 60, "Andante");
        setVisible(false);
    }

    @Action
    public void andantino() {
        tempo = new ElementMusicalTempo(moment, 80, "Andantino");
        setVisible(false);
    }

    @Action
    public void allegretto() {
        tempo = new ElementMusicalTempo(moment, 100, "Allegretto");
        setVisible(false);
    }

    @Action
    public void allegro() {
        tempo = new ElementMusicalTempo(moment, 150, "Allegro");
        setVisible(false);
    }

    @Action
    public void presto() {
        tempo = new ElementMusicalTempo(moment, 200, "Presto");
        setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables

}
